version: "3.9"
services:
  redis:
    container_name: "redis_ru202"
    image: "redis/redis:stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--appendonly yes --save ""
    volumes:
      - $PWD/redisdata:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
